import { ChampionType } from '../types/championsTypes';

export const champions: ChampionType[] = [
  {name: 'Aatrox', role: ['top'], type: ['ad'], nameBase: 'aatrox', range: ['melee']},
  {name: 'Ahri', role: ['mid'], type: ['ap'], nameBase: 'ahri', range: ['ranged']},
  {name: 'Akali', role: ['mid', 'top'], type: ['ap'], nameBase: 'akali', range: ['melee']},
  {name: 'Akshan', role: ['mid'], type: ['ad'], nameBase: 'akshan', range: ['ranged']},
  {name: 'Alistar', role: ['sup'], type: ['tank'], nameBase: 'alistar', range: ['melee']},
  {name: 'Amumu', role: ['jg'], type: ['tank'], nameBase: 'amumu', range: ['melee']},
  {name: 'Anivia', role: ['mid'], type: ['ap'], nameBase: 'anivia', range: ['ranged']},
  {name: 'Annie', role: ['mid'], type: ['ap'], nameBase: 'annie', range: ['ranged']},
  {name: 'Aphelios', role: ['adc'], type: ['ad'], nameBase: 'aphelios', range: ['ranged']},
  {name: 'Ashe', role: ['adc'], type: ['ad'], nameBase: 'ashe', range: ['ranged']},
  {name: 'Aurelion Sol', role: ['mid'], type: ['ap'], nameBase: 'aurelionsol', range: ['ranged']},
  {name: 'Azir', role: ['mid'], type: ['ap'], nameBase: 'azir', range: ['ranged']},
  {name: 'Bard', role: ['sup'], type: ['ap'], nameBase: 'bard', range: ['ranged']},
  {name: 'Bel\'Veth', role: ['jg'], type: ['ad'], nameBase: 'belveth', range: ['melee']},
  {name: 'Blitzcrank', role: ['sup'], type: ['ap', 'tank'], nameBase: 'blitzcrank', range: ['melee']},
  {name: 'Brand', role: ['sup'], type: ['ap'], nameBase: 'brand', range: ['ranged']},
  {name: 'Braum', role: ['sup'], type: ['tank'], nameBase: 'braum', range: ['melee']},
  {name: 'Briar', role: ['jg'], type: ['ad'], nameBase: 'briar', range: ['melee']},
  {name: 'Caitlyn', role: ['adc'], type: ['ad'], nameBase: 'caitlyn', range: ['ranged']},
  {name: 'Camille', role: ['top'], type: ['ad'], nameBase: 'camille', range: ['melee']},
  {name: 'Cassiopeia', role: ['mid'], type: ['ap'], nameBase: 'cassiopeia', range: ['ranged']},
  {name: 'Cho\'Gath', role: ['top'], type: ['ap', 'tank'], nameBase: 'chogath', range: ['melee']},
  {name: 'Corki', role: ['mid'], type: ['ap', 'ad'], nameBase: 'corki', range: ['ranged']},
  {name: 'Darius', role: ['top'], type: ['ad'], nameBase: 'darius', range: ['melee']},
  {name: 'Diana', role: ['mid', 'jg'], type: ['ap'], nameBase: 'diana', range: ['melee']},
  {name: 'Dr. Mundo', role: ['top'], type: ['ap', 'tank'], nameBase: 'drmundo', range: ['melee']},
  {name: 'Draven', role: ['adc'], type: ['ad'], nameBase: 'draven', range: ['ranged']},
  {name: 'Ekko', role: ['mid', 'jg'], type: ['ap'], nameBase: 'ekko', range: ['melee']},
  {name: 'Elise', role: ['jg'], type: ['ap'], nameBase: 'elise', range: ['melee', 'ranged']},
  {name: 'Evelynn', role: ['jg'], type: ['ap'], nameBase: 'evelynn', range: ['melee']},
  {name: 'Ezreal', role: ['adc'], type: ['ad'], nameBase: 'ezreal', range: ['ranged']},
  {name: 'Fiddlesticks', role: ['jg'], type: ['ap'], nameBase: 'fiddlesticks', range: ['ranged']},
  {name: 'Fiora', role: ['top'], type: ['ad'], nameBase: 'fiora', range: ['melee']},
  {name: 'Fizz', role: ['mid'], type: ['ap'], nameBase: 'fizz', range: ['melee']},
  {name: 'Galio', role: ['mid'], type: ['ap', 'tank'], nameBase: 'galio', range: ['melee']},
  {name: 'Gangplank', role: ['top'], type: ['ad'], nameBase: 'gangplank', range: ['melee']},
  {name: 'Garen', role: ['top'], type: ['ad', 'tank'], nameBase: 'garen', range: ['melee']},
  {name: 'Gnar', role: ['top'], type: ['ad', 'tank'], nameBase: 'gnar', range: ['melee', 'ranged']},
  {name: 'Gragas', role: ['top', 'jg'], type: ['ap', 'tank'], nameBase: 'gragas', range: ['melee']},
  {name: 'Graves', role: ['jg'], type: ['ad'], nameBase: 'graves', range: ['ranged']},
  {name: 'Gwen', role: ['top'], type: ['ap'], nameBase: 'gwen', range: ['melee']},
  {name: 'Hecarim', role: ['jg'], type: ['ad'], nameBase: 'hecarim', range: ['melee']},
  {name: 'Heimerdinger', role: ['mid', 'top'], type: ['ap'], nameBase: 'heimerdinger', range: ['ranged']},
  {name: 'Hwei', role: ['mid', 'sup'], type: ['ap'], nameBase: 'hwei', range: ['ranged']},
  {name: 'Illaoi', role: ['top'], type: ['ad', 'tank'], nameBase: 'illaoi', range: ['melee']},
  {name: 'Irelia', role: ['top', 'mid'], type: ['ad'], nameBase: 'irelia', range: ['melee']},
  {name: 'Ivern', role: ['jg'], type: ['ap'], nameBase: 'ivern', range: ['ranged']},
  {name: 'Janna', role: ['sup'], type: ['ap'], nameBase: 'janna', range: ['ranged']},
  {name: 'Jarvan IV', role: ['jg'], type: ['ad'], nameBase: 'jarvaniv', range: ['melee']},
  {name: 'Jax', role: ['top'], type: ['ad'], nameBase: 'jax', range: ['melee']},
  {name: 'Jayce', role: ['top', 'mid'], type: ['ad'], nameBase: 'jayce', range: ['melee', 'ranged']},
  {name: 'Jhin', role: ['adc'], type: ['ad'], nameBase: 'jhin', range: ['ranged']},
  {name: 'Jinx', role: ['adc'], type: ['ad'], nameBase: 'jinx', range: ['ranged']},
  {name: 'K\'Sante', role: ['top'], type: ['ad', 'tank'], nameBase: 'ksante', range: ['melee']},
  {name: 'Kai\'Sa', role: ['adc'], type: ['ad'], nameBase: 'kaisa', range: ['ranged']},
  {name: 'Kalista', role: ['adc'], type: ['ad'], nameBase: 'kalista', range: ['ranged']},
  {name: 'Karma', role: ['sup', 'mid'], type: ['ap'], nameBase: 'karma', range: ['ranged']},
  {name: 'Karthus', role: ['jg'], type: ['ap'], nameBase: 'karthus', range: ['ranged']},
  {name: 'Kassadin', role: ['mid'], type: ['ap'], nameBase: 'kassadin', range: ['melee']},
  {name: 'Katarina', role: ['mid'], type: ['ap', 'ad'], nameBase: 'katarina', range: ['melee']},
  {name: 'Kayle', role: ['top'], type: ['ap', 'ad'], nameBase: 'kayle', range: ['melee', 'ranged']},
  {name: 'Kayn', role: ['jg'], type: ['ad'], nameBase: 'kayn', range: ['melee']},
  {name: 'Kennen', role: ['top'], type: ['ap'], nameBase: 'kennen', range: ['ranged']},
  {name: 'Kha\'Zix', role: ['jg'], type: ['ad'], nameBase: 'khazix', range: ['melee']},
  {name: 'Kindred', role: ['jg'], type: ['ad'], nameBase: 'kindred', range: ['ranged']},
  {name: 'Kled', role: ['top'], type: ['ad'], nameBase: 'kled', range: ['melee']},
  {name: 'Kog\'Maw', role: ['adc'], type: ['ad'], nameBase: 'kogmaw', range: ['ranged']},
  {name: 'LeBlanc', role: ['mid'], type: ['ap', 'ad'], nameBase: 'leblanc', range: ['ranged']},
  {name: 'Lee Sin', role: ['jg'], type: ['ad'], nameBase: 'leesin', range: ['melee']},
  {name: 'Leona', role: ['sup'], type: ['tank'], nameBase: 'leona', range: ['melee']},
  {name: 'Lillia', role: ['jg'], type: ['ap'], nameBase: 'lillia', range: ['melee']},
  {name: 'Lissandra', role: ['mid'], type: ['ap'], nameBase: 'lissandra', range: ['ranged']},
  {name: 'Lucian', role: ['adc'], type: ['ad'], nameBase: 'lucian', range: ['ranged']},
  {name: 'Lulu', role: ['sup'], type: ['ap'], nameBase: 'lulu', range: ['ranged']},
  {name: 'Lux', role: ['sup', 'mid'], type: ['ap'], nameBase: 'lux', range: ['ranged']},
  {name: 'Malphite', role: ['top'], type: ['tank', 'ap'], nameBase: 'malphite', range: ['melee']},
  {name: 'Malzahar', role: ['mid'], type: ['ap'], nameBase: 'malzahar', range: ['ranged']},
  {name: 'Maokai', role: ['sup', 'jg', 'top'], type: ['ap', 'tank'], nameBase: 'maokai', range: ['melee']},
  {name: 'Master Yi', role: ['jg'], type: ['ad'], nameBase: 'masteryi', range: ['melee']},
  {name: 'Millio', role: ['sup'], type: ['ap'], nameBase: 'millio', range: ['ranged']},
  {name: 'Miss Fortune', role: ['adc'], type: ['ad'], nameBase: 'missfortune', range: ['ranged']},
  {name: 'Morderkaiser', role: ['top'], type: ['ap', 'tank'], nameBase: 'mordekaiser', range: ['melee']},
  {name: 'Morgana', role: ['sup'], type: ['ap'], nameBase: 'morgana', range: ['ranged']},
  {name: 'Naafiri', role: ['mid'], type: ['ad'], nameBase: 'naafiri', range: ['melee']},
  {name: 'Nami', role: ['sup'], type: ['ap'], nameBase: 'nami', range: ['ranged']},
  {name: 'Nasus', role: ['top'], type: ['ad', 'tank'], nameBase: 'nasus', range: ['melee']},
  {name: 'Nautilus', role: ['sup'], type: ['tank'], nameBase: 'nautilus', range: ['melee']},
  {name: 'Neeko', role: ['mid', 'sup'], type: ['ap'], nameBase: 'neeko', range: ['ranged']},
  {name: 'Nidalee', role: ['jg'], type: ['ap'], nameBase: 'nidalee', range: ['ranged', 'melee']},
  {name: 'Nilah', role: ['adc'], type: ['ad'], nameBase: 'nilah', range: ['ranged']},
  {name: 'Nocturne', role: ['jg'], type: ['ad'], nameBase: 'nocturne', range: ['melee']},
  {name: 'Nunu & Willump', role: ['jg'], type: ['ap', 'tank'], nameBase: 'nunu', range: ['melee']},
  {name: 'Olaf', role: ['jg', 'top'], type: ['ad'], nameBase: 'olaf', range: ['melee']},
  {name: 'Orianna', role: ['mid'], type: ['ap'], nameBase: 'orianna', range: ['ranged']},
  {name: 'Ornn', role: ['top'], type: ['tank'], nameBase: 'ornn', range: ['melee']},
  {name: 'Pantheon', role: ['sup', 'top', 'mid'], type: ['ad'], nameBase: 'pantheon', range: ['melee']},
  {name: 'Poppy', role: ['jg', 'top'], type: ['tank'], nameBase: 'poppy', range: ['melee']},
  {name: 'Pyke', role: ['sup'], type: ['ad'], nameBase: 'pyke', range: ['melee']},
  {name: 'Qiyana', role: ['mid'], type: ['ad'], nameBase: 'qiyana', range: ['melee']},
  {name: 'Quinn', role: ['top'], type: ['ad'], nameBase: 'quinn', range: ['ranged']},
  {name: 'Rakan', role: ['sup'], type: ['tank'], nameBase: 'rakan', range: ['melee']},
  {name: 'Rammus', role: ['jg'], type: ['tank'], nameBase: 'rammus', range: ['melee']},
  {name: 'Rek\'Sai', role: ['jg', 'top'], type: ['ad'], nameBase: 'reksai', range: ['melee']},
  {name: 'Rell', role: ['sup'], type: ['tank'], nameBase: 'rell', range: ['melee']},
  {name: 'Renata Glasc', role: ['sup'], type: ['ap'], nameBase: 'renata', range: ['ranged']},
  {name: 'Renekton', role: ['top'], type: ['ad'], nameBase: 'renekton', range: ['melee']},
  {name: 'Rengar', role: ['jg'], type: ['ad'], nameBase: 'rengar', range: ['melee']},
  {name: 'Riven', role: ['top'], type: ['ad'], nameBase: 'riven', range: ['melee']},
  {name: 'Rumble', role: ['top'], type: ['ap'], nameBase: 'rumble', range: ['melee']},
  {name: 'Ryze', role: ['mid', 'top'], type: ['ap'], nameBase: 'ryze', range: ['ranged']},
  {name: 'Samira', role: ['adc'], type: ['ad'], nameBase: 'samira', range: ['ranged']},
  {name: 'Sejuani', role: ['jg'], type: ['tank'], nameBase: 'sejuani', range: ['melee']},
  {name: 'Senna', role: ['sup', 'adc'], type: ['ad'], nameBase: 'senna', range: ['ranged']},
  {name: 'Seraphine', role: ['sup'], type: ['ap'], nameBase: 'seraphine', range: ['ranged']},
  {name: 'Sett', role: ['top'], type: ['ad'], nameBase: 'sett', range: ['melee']},
  {name: 'Shaco', role: ['jg', 'sup'], type: ['ad', 'ap'], nameBase: 'shaco', range: ['melee']},
  {name: 'Shen', role: ['top'], type: ['tank'], nameBase: 'shen', range: ['melee']},
  {name: 'Shyvana', role: ['jg'], type: ['ap', 'tank'], nameBase: 'shyvana', range: ['melee']},
  {name: 'Singed', role: ['top'], type: ['ap', 'tank'], nameBase: 'singed', range: ['melee']},
  {name: 'Sion', role: ['top'], type: ['tank'], nameBase: 'sion', range: ['melee']},
  {name: 'Sivir', role: ['adc'], type: ['ad'], nameBase: 'sivir', range: ['ranged']},
  {name: 'Skarner', role: ['jg', 'top'], type: ['tank'], nameBase: 'skarner', range: ['melee']},
  {name: 'Smolder', role: ['adc'], type: ['ad'], nameBase: 'smolder', range: ['ranged']},
  {name: 'Sona', role: ['sup'], type: ['ap'], nameBase: 'sona', range: ['ranged']},
  {name: 'Soraka', role: ['sup'], type: ['ap'], nameBase: 'soraka', range: ['ranged']},
  {name: 'Swain', role: ['sup'], type: ['ap'], nameBase: 'swain', range: ['ranged']},
  {name: 'Sylas', role: ['mid'], type: ['ap'], nameBase: 'sylas', range: ['melee']},
  {name: 'Syndra', role: ['mid'], type: ['ap'], nameBase: 'syndra', range: ['ranged']},
  {name: 'Tahm Kench', role: ['top', 'sup'], type: ['tank'], nameBase: 'tahmkench', range: ['melee']},
  {name: 'Taliyah', role: ['mid', 'jg'], type: ['ap'], nameBase: 'taliyah', range: ['ranged']},
  {name: 'Talon', role: ['mid', 'jg'], type: ['ad'], nameBase: 'talon', range: ['melee']},
  {name: 'Taric', role: ['sup'], type: ['tank'], nameBase: 'taric', range: ['melee']},
  {name: 'Teemo', role: ['top'], type: ['ap'], nameBase: 'teemo', range: ['ranged']},
  {name: 'Thresh', role: ['sup'], type: ['tank'], nameBase: 'thresh', range: ['ranged']},
  {name: 'Tristana', role: ['adc', 'mid'], type: ['ad'], nameBase: 'tristana', range: ['ranged']},
  {name: 'Trundle', role: ['top'], type: ['ad'], nameBase: 'trundle', range: ['melee']},
  {name: 'Tryndamere', role: ['top'], type: ['ad'], nameBase: 'tryndamere', range: ['melee']},
  {name: 'Twisted Fate', role: ['mid'], type: ['ad', 'ap'], nameBase: 'twistedfate', range: ['ranged']},
  {name: 'Twitch', role: ['adc'], type: ['ad'], nameBase: 'twitch', range: ['ranged']},
  {name: 'Udyr', role: ['jg'], type: ['ap', 'tank'], nameBase: 'udyr', range: ['melee']},
  {name: 'Urgot', role: ['top'], type: ['ad', 'tank'], nameBase: 'urgot', range: ['ranged']},
  {name: 'Varus', role: ['adc'], type: ['ad'], nameBase: 'varus', range: ['ranged']},
  {name: 'Vayne', role: ['adc', 'top'], type: ['ad'], nameBase: 'vayne', range: ['ranged']},
  {name: 'Veigar', role: ['mid'], type: ['ap'], nameBase: 'veigar', range: ['ranged']},
  {name: 'Vel\'Koz', role: ['sup'], type: ['ap'], nameBase: 'velkoz', range: ['ranged']},
  {name: 'Vex', role: ['mid'], type: ['ap'], nameBase: 'vex', range: ['ranged']},
  {name: 'Vi', role: ['jg'], type: ['ad'], nameBase: 'vi', range: ['melee']},
  {name: 'Viego', role: ['jg'], type: ['ad'], nameBase: 'viego', range: ['melee']},
  {name: 'Viktor', role: ['mid'], type: ['ap'], nameBase: 'viktor', range: ['ranged']},
  {name: 'Vladimir', role: ['mid'], type: ['ap'], nameBase: 'vladimir', range: ['ranged']},
  {name: 'Volibear', role: ['top', 'jg'], type: ['tank'], nameBase: 'volibear', range: ['melee']},
  {name: 'Warwick', role: ['top', 'jg'], type: ['ad'], nameBase: 'warwick', range: ['melee']},
  {name: 'Wukong', role: ['top', 'jg'], type: ['ad'], nameBase: 'wukong', range: ['melee']},
  {name: 'Xayah', role: ['adc'], type: ['ad'], nameBase: 'xayah', range: ['ranged']},
  {name: 'Xerath', role: ['sup', 'mid'], type: ['ap'], nameBase: 'xerath', range: ['ranged']},
  {name: 'Xin Zhao', role: ['jg'], type: ['ad'], nameBase: 'xinzhao', range: ['melee']},
  {name: 'Yasuo', role: ['mid'], type: ['ad'], nameBase: 'yasuo', range: ['melee']},
  {name: 'Yone', role: ['mid', 'top'], type: ['ad'], nameBase: 'yone', range: ['melee']},
  {name: 'Yorick', role: ['top'], type: ['ad', 'tank'], nameBase: 'yorick', range: ['melee']},
  {name: 'Yuumi', role: ['sup'], type: ['ap'], nameBase: 'yuumi', range: ['ranged']},
  {name: 'Zac', role: ['jg', 'top'], type: ['tank'], nameBase: 'zac', range: ['melee']},
  {name: 'Zed', role: ['mid'], type: ['ad'], nameBase: 'zed', range: ['melee']},
  {name: 'Zeri', role: ['adc'], type: ['ad'], nameBase: 'zeri', range: ['ranged']},
  {name: 'Ziggs', role: ['mid', 'adc'], type: ['ap'], nameBase: 'ziggs', range: ['ranged']},
  {name: 'Zilean', role: ['sup'], type: ['ap'], nameBase: 'zilean', range: ['ranged']},
  {name: 'Zoe', role: ['mid'], type: ['ap'], nameBase: 'zoe', range: ['ranged']},
  {name: 'Zyra', role: ['sup'], type: ['ap'], nameBase: 'zyra', range: ['ranged']},
]